class PurchaseNotFoundException(Exception): ...
class CannotBuyOwnProductException(Exception): ...
class PurchaseRequestAlreadyExistsException(Exception): ...
class PurchaseAlreadyProcessedException(Exception): ...
class UserCannotAcceptPurchaseException(Exception): ...
class PurchaseNotYetCompleteException(Exception): ...
class UserDidNotParticipateInPurchaseException(Exception): ...