class UsernameAlreadyUsedException(Exception): ...
class VerificationCodeNotFoundException(Exception): ...
class UserIsAlreadyActiveException(Exception): ...
class VerificationCodeUsedException(Exception): ...
class InvalidVerificationCodeException(Exception): ...
class ServerNotDetectTGException(Exception): ...