"""Added comment to purchase table

Revision ID: 283de4c1fd62
Revises: 2b97cd9fe272
Create Date: 2025-10-23 11:37:06.122432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '283de4c1fd62'
down_revision: Union[str, Sequence[str], None] = '2b97cd9fe272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('comment', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'comment')
    # ### end Alembic commands ###
