"""modify encode_id to verification code model

Revision ID: 35924a31d42a
Revises: 693b293f5d2b
Create Date: 2025-10-07 01:26:00.634476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35924a31d42a'
down_revision: Union[str, Sequence[str], None] = '693b293f5d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_codes', 'encode_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_codes', 'encode_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
