"""Added refusal to purchase table

Revision ID: 5bad06667bc9
Revises: 283de4c1fd62
Create Date: 2025-10-23 19:55:19.483520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bad06667bc9'
down_revision: Union[str, Sequence[str], None] = '283de4c1fd62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM purchases")
    op.add_column('purchases', sa.Column('refusal', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'refusal')
    # ### end Alembic commands ###
