"""Add created_at and verified_at to user model

Revision ID: 75046f050c26
Revises: 35924a31d42a
Create Date: 2025-10-07 12:38:28.702971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75046f050c26'
down_revision: Union[str, Sequence[str], None] = '35924a31d42a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM users")
    op.execute("DELETE FROM verification_codes")
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('verified_at', sa.DateTime(), nullable=True))
    op.add_column('verification_codes', sa.Column('activate', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_codes', 'activate')
    op.drop_column('users', 'verified_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
