"""Add tg_user_id and tg_username to verification code model

Revision ID: c264a85cac85
Revises: 75046f050c26
Create Date: 2025-10-09 19:38:01.558672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c264a85cac85'
down_revision: Union[str, Sequence[str], None] = '75046f050c26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_codes', sa.Column('tg_user_id', sa.Integer(), nullable=True))
    op.add_column('verification_codes', sa.Column('tg_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_codes', 'tg_username')
    op.drop_column('verification_codes', 'tg_user_id')
    # ### end Alembic commands ###
