"""Added is_active to products

Revision ID: e46eb871a22e
Revises: 2f904fa2593d
Create Date: 2025-10-28 20:08:20.409367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46eb871a22e'
down_revision: Union[str, Sequence[str], None] = '2f904fa2593d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM reviews")
    op.execute("DELETE FROM purchases")
    op.execute("DELETE FROM products")
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_active')
    # ### end Alembic commands ###
